show databases;
use emp;
show tables;
drop table emp1;

desc emp;
select * from emp;
 
##  COPY STRUCTURE OF THE TABLE ##
CREATE TABLE EMP1 LIKE EMP;

##     COPY RECORDS OF THE TABLE    ##
INSERT INTO EMP1 SELECT * FROM EMP;

SELECT * FROM EMP1;

DESC EMP1;
SHOW TABLES;

##  COPY STRUCTURE & RECORDS OF THE TBALE  ##
CREATE TABLE EMP2 AS (SELECT * FROM EMP);

DESC EMP2;
SELECT * FROM EMP2;

## UPDATE MULTIPLE CHANGES IN ONE ROW  ##
UPDATE EMP2 SET EMP_PF=900,AGE=32 WHERE EMP_ID=5;

select * from emp2;